#!/bin/bash

#This script gets the volume. It looks at both the left, and the right
#channel, and averages their volumes (it accounts only for those that are on)

VOL=$(amixer -D pulse sget Master| awk '/\[(.*)\]/{if($6 ~/on/) {c++;sum+=substr($5, 2, length($5)-2)}} END {if(c>0) {print sum/c}}')

if [ -z "$VOL" ];then
  echo "  "
else
  if [ $VOL -lt "50" ]; then
    echo "   $VOL% "
  else 
    echo "   $VOL% "
  fi
fi



