#!/bin/bash
# Args:
# $1: role to be assigned to the terminal window
# $2: command to run in the terminal window
# Example:
#         ./open_scratchpad rofi_scratchpad rofi
#

WindowName=$1
Command=$2
if [ -z "$(wmctrl -l |grep -v $0 | grep $WindowName)" ]; then # && # check if 
  i3-msg "exec --no-startup-id gnome-terminal --title=\"$WindowName\" --geometry=125x25 -x $Command;"
  sleep 0.5
  i3-msg "[title=$WindowName] floating enable;" 
  i3-msg "[title=$WindowName] move scratchpad;" 
  i3-msg "[title=$WindowName] border pixel 5;"
fi
i3-msg "[title=$WindowName] scratchpad show; [title=$WindowName] move position center;"

