#!/bin/bash

get_match()
{
  selection=$(echo -e "$1" | rofi -dmenu -p "$2" -config ~/.dotfiles/rofi/config.rasi)
  [[ -z "$selection" ]] && exit 1
  does_match_=$(echo -e "$1" | grep "$selection")
  [[ -n "$1" ]] && [[ -z "$does_match_" ]] && exit 1
  echo "$selection"
}

mountable=$(lsblk -lp | grep "part \+$"|awk '{print $1,"("$4")"}'|sed 's/,/./g')
[[ "$mountable" = "" ]] && exit 1
selection=$(get_match "$mountable" "Partition" | awk '{print $1}')

dirs=$(find /mnt /media /home -type d -maxdepth 3 2>/dev/null)
mount_point=$(echo -e "$dirs" | rofi -dmenu -p "Where to mount" -config ~/.dotfiles/rofi/config.rasi)
[[ "$mount_point" = "" ]] && exit 1
if [[ ! -d "$mount_point" ]];then
  mk_=$(echo -e "Yes\nNo"|rofi -dmenu -p "Destination does not exist. Create it" -config ~/.dotfiles/rofi/config.rasi)
  [[ "$mk_" = "Yes" ]] && sudo mkdir -p "$mount_point" || exit 1
fi

sudo mount "$selection" "$mount_point"
