#!/bin/zsh
#This script provides a rofi menu interface for wifi control
#It uses and requires nmcli

toggle_entry="WiFi"
create_option="New connection"

fields="SSID,BARS,SECURITY"
lines_full=$(nmcli --fields $fields dev wifi list|sed "/\(^--\|$(echo $fields|cut -d',' -f1)\)/d"|sed 's/\s\+/  /g')
lines=$(echo -e "$lines_full"| awk -F "  " '{print $1"  "$2}')
cons=$(nmcli con show)
state=$(nmcli -fields WIFI g)
current=$(iwgetid -r)
ssid_field=$(echo -e $fields| awk  'BEGIN{FS=","}{for(i=1;i<=NF;++i) {if($i ~ "SSID") print i}}')

#Checks if wifi is currently enabled
if [[ "$state" =~ "enabled" ]]; then
	toggle="$toggle_entry off"
elif [[ "$state" =~ "disabled" ]]; then
	toggle="$toggle_entry on"
fi

#Takes input from the user using a rofi menu
selection=$(echo -e "$toggle\n$lines\n$create_option" | rofi -dmenu -p "WiFi" -config ~/.dotfiles/rofi/config.rasi)
selected_ssid=$(echo $selection|sed 's/\s\{2,\}/|/g'|awk -F "|" "{print \$$ssid_field}" )

if [ "$selected_ssid" = "$create_option" ]; then
  manual_ssid=$(echo "Enter the SSID of the network." | rofi -dmenu -p "SSID" -config ~/.dotfiles/rofi/config.rasi)
  manual_password=$(echo "Enter the Password of the network (or leave blank)." | rofi -dmenu -p "Password" -config ~/.dotfiles/rofi/config.rasi)
  if [ "$manual_password" = "" ];then
    nmcli dev wifi con "$manual_ssid"
  else
    nmcli dev wifi con "$manual_ssid" password "$manual_password"
  fi
elif [ "$selected_ssid" = "$toggle_entry on" ];then
  nmcli radio wifi on
elif [ "$selected_ssid" = "$toggle_entry off" ];then
  nmcli radio wifi off
elif [[ -n "$selection" ]];then
  matches=$(echo -e "$cons" |sed 's/\s\{2,\}/|/g'|awk -F "|" "/$selected_ssid/{print \$1}")
  if [[ -n "$matches" ]];then
    n_matches=$(echo -e $matches |wc -l)
    if [[ "$n_matches" -eq "1" ]]; then
      nmcli con up "$selected_ssid"
    else
      chosen_cons = $(echo -e "$matches" | rofi -dmenu -p "Which" -config ~/.dotfiles/rofi/config.rasi)
      nmcli con up "$chosen_cons"
    fi
  else
    sec=$(echo $lines_full|grep $selection| awk '/(WPA|WEP)/')
    if [[ -n "$sec" ]];then
      password_=$(echo "Enter password of the newtork (or leave blank)." | rofi -dmenu -p "Password" -config ~/.dotfiles/rofi/config.rasi)
    fi
    nmcli dev wifi con "$selection" password "$password_"
  fi
fi
