#!/bin/bash

to_play=$(rofi -dmenu -p "mpv" -theme ~/.dotfiles/var/rofi_mpv/theme.rasi)
[[ -z "$to_play" ]] && exit 1
is_acestream=$(awk "/^acestream/" <(echo "$to_play"))
if [ -n "$is_acestream" ];then
  acestream-launcher --player mpv "$to_play"
else
  mpv "$to_play"
fi
