#!/bin/bash

toggle_entry="WiFi"

fields=$(cat ~/.dotfiles/var/rofi_wifi/fields)
lines=$(nmcli --fields $fields dev wifi list|sed "/\(^--\|$(echo $fields|cut -d',' -f1)\)/d"|sed 's/\s\+/ /g')
cons=$(nmcli con show)
state=$(nmcli -fields WIFI g)
current=$(iwgetid -r)
ssid_field=$(echo -e $fields| awk  'BEGIN{FS=","}{for(i=1;i<=NF;++i) {if($i ~ "SSID") print i}}')

if [[ "$state" =~ "enabled" ]]; then
	toggle="$toggle_entry off"
elif [[ "$state" =~ "disabled" ]]; then
	toggle="$toggle_entry on"
fi

selection=$(echo -e "$toggle\nmanual\n$lines" | rofi -dmenu -p "WiFi SSID" -config ~/.dotfiles/rofi/config.rasi)
selected_ssid=$(echo $selection|sed 's/\s\{1,\}/|/g'|awk 'BEGIN {FS="|"}{print $1}')

if [ "$selected_ssid" = "manual" ]; then
  manual_ssid=$(echo "Enter the SSID of the network." | rofi -dmenu -p "SSID" -config ~/.dotfiles/rofi/config.rasi)
  manual_password=$(echo "Enter the Password of the network (or leave blank)." | rofi -dmenu -p "Password" -config ~/.dotfiles/rofi/config.rasi)
  if [ "$manual_password" = "" ];then
    nmcli dev wifi con "$manual_ssid"
  else
    nmcli dev wifi con "$manual_ssid" password "$manual_password"
  fi
elif [ "$selected_ssid" = "$toggle_entry on"];then
  nmcli radio wifi on
elif [ "$selected_ssid" = "$toggle_entry off"];then
  nmcli radio wifi off
fi
