#!/bin/bash
id=$(xinput -list | grep "Virtual core keyboard"|sed 's/\s\+/ /g'|cut -d"=" -f2|cut -d" " -f1)
setxkbmap -device $id -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps
#but caps lock is escape when pressed alone
to_test="xcape -e Control_L Escape"
test=$(ps aux |grep "$to_test"|grep -v grep)
if [[ -z "$test"  ]]; then
  xcape -e 'Control_L=Escape'
fi
#id of the touchpad
id=$(xinput list|grep -i touchpad|grep -oE "id=[0-9]+"|cut -d'=' -f2)

#enable natural scaling
prop_id=$(xinput list-props $id|grep -i natural|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#enable horizontal scroll
prop_id=$(xinput list-props $id|grep -i hor|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#enable tap to click
prop_id=$(xinput list-props $id|grep -i tapping|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#enable tap to drag
prop_id=$(xinput list-props $id|grep -i "tapping drag"|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#disable touchpad while typing
prop_id=$(xinput list-props $id|grep -i "disable while typing"|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#set mouse acceleration
prop_id=$(xinput list-props $id|grep -i "accel speed"|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 0.5
#disable middle button
xinput set-button-map $id 1 1 3

