#!/bin/bash
to_run="xcape -e Control_L Escape"
test=$(ps aux |grep "$to_run"|grep -v grep)
#caps-lock as control
id=$(xinput -list | awk "/Virtual core keyboard/"|sed 's/\s\+/ /g'|cut -d"=" -f2|cut -d" " -f1)
setxkbmap -device $id -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps

if [[ -z "$test"  ]]; then
  to_run
fi
#id of the touchpad
id=$(xinput list|grep Touchpad|grep -oE "id=[0-9]+"|cut -d'=' -f2)
prop_id=$(xinput list-props $id|grep -i natural|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#enable horizontal scroll
prop_id=$(xinput list-props $id|grep -i hor|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#enable tap to click
prop_id=$(xinput list-props $id|grep -i tapping|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#disable touchpad while typing
prop_id=$(xinput list-props $id|grep -i "disable while typing"|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 1
#set mouse acceleration
prop_id=$(xinput list-props $id|grep -i "accel speed"|head -n1|cut -d"(" -f2|cut -d")" -f1)
xinput set-prop $id $prop_id 0.2
#disable middle button
xinput set-button-map $id 1 0 3
